// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yilowtgfwfawpcqrugwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpbG93dGdmd2Zhd3BjcXJ1Z3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTA0NzEsImV4cCI6MjA2MzY4NjQ3MX0.3VqYtM0rFRnhMmdoIRqd918h6H1yCJElXg5UABCOazk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);